### PR TITLE
Donation receipts

### PR DESCRIPTION
**Pull request by kuboschek**

### CODE REVIEW

**Comment by tkw1536** [comment]
The merge seems to have messed up the migrations, we will have to merge those.

**Comment by tkw1536** [comment]
We'll also have to re-work the text in https://github.com/JacobsAlumni/MemberManagement/blob/main/payments/templates/payments/view/004_info_stripe.html#L7-L9, as we now *do* have a copy.

**Comment by kuboschek** [comment]
> We'll also have to re-work the text in https://github.com/JacobsAlumni/MemberManagement/blob/main/payments/templates/payments/view/004_info_stripe.html#L7-L9, as we now _do_ have a copy.

This is adressed in the latest commit.

**Comment by tkw1536** [comment]
Note to self: Once we merge and publish this next year we need to update https://github.com/JacobsAlumni/jacobs-alumni.de/blob/main/pages/privacy.ts.

**Pull request merged**
